AllCops:
  TargetRubyVersion: 3.0

 # Exclude:
    # - 'polydif_ych.gemspec'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
 EnforcedStyle: double_quotes

 Style/Documentation:
  Enabled: false

 Naming/MethodName:
  EnforcedStyle: snake_case

 Naming/ClassAndModuleCamelCase:
  Enabled: true

 Naming/FileName:
  EnforcedStyle: snake_case


 Layout/SpaceAfterComma:
  Enabled: true