AllCops:
  TargetRubyVersion: 3.0

 # Exclude:
    # - 'polydif_ych.gemspec'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
 EnforcedStyle: double_quotes

Style/Documentation:
 Enabled: false

Metrics/AbcSize:
 Enabled: false

Metrics/CyclomaticComplexity:
 Enabled: false

Metrics/MethodLength:
 Enabled: false

Metrics/PerceivedComplexity:
 Enabled: false

Style/PerlBackrefs:
 Enabled: false

Style/StringConcatenation:
 Enabled: false

Style/IfUnlessModifier:
 Enabled: false

Style/RedundantRegexpEscape:
 Enabled: false

Lint/UnreachableCode:
 Enabled: false

Naming/MethodName:
 EnforcedStyle: snake_case

Naming/ClassAndModuleCamelCase:
 Enabled: true

Naming/FileName:
 EnforcedStyle: snake_case

Layout/SpaceAfterComma:
 Enabled: true

Layout/EmptyLineAfterMagicComment:
 Enabled: false
